name: Create prerelease

on:
  release:
    types: [prereleased]

jobs:
  prerelease-image-manifest:
    name: Prerelease image and upload manifests
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: newrelic/nri-ecs
      DOCKER_PLATFORMS: "linux/amd64,linux/arm64,linux/arm" # Must be consistent with the matrix make compile-multiarch.
      S3_BASE_FOLDER: s3://nr-downloads-main/infrastructure_agent
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Generate version from tag
        run: |
          echo "${{ github.event.release.tag_name }}" | grep -E '^v[0-9.]*[0-9]$'
          NRI_VERSION=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
          echo "NRI_VERSION=$NRI_VERSION" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_TAG=$NRI_VERSION" >> $GITHUB_ENV

      - name: Build integration
        run: |
          make compile-multiarch RELEASE_VERSION=$NRI_VERSION

      - name: Set image tag
        run: |
          echo "DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG}-pre" >> $GITHUB_ENV

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.FSI_DOCKERHUB_USERNAME }}
          password: ${{ secrets.FSI_DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker buildx build --push --platform=$DOCKER_PLATFORMS \
            -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG \
            .

      - name: Set S3 test folder
        run: |
          echo "S3_BASE_FOLDER=$S3_BASE_FOLDER/test" >> $GITHUB_ENV

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.COREINT_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.COREINT_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload configuration files to https://download.newrelic.com
        run: |
          make upload_manifests RELEASE_VERSION=$NRI_VERSION NRI_ECS_IMAGE_TAG=$DOCKER_IMAGE_TAG
